[package]
name = "devalang_macros"
description = "Macros for Devalang"
license = "MIT"
version = "0.0.1"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
