pub mod automation;
pub mod encoders;
pub mod effects;
pub mod evaluator;
pub mod events;
pub mod fx;
pub mod generator;
pub mod graph;
pub mod interpreter;
pub mod lfo;
pub mod midi;
pub mod mixer;
pub mod nodes;
pub mod playback;
#[cfg(feature = "cli")]
pub mod samples;
pub mod settings;
pub mod synth;
