[package]
name = "devalang_types"
version = "0.0.2"
description = "Types and traits for Devalang"
license = "MIT"
authors = ["Devaloop <contact@devaloop.com>"]
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
