/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const parse: (a: number, b: number, c: number, d: number) => [number, number, number];
export const check_syntax: (a: number, b: number) => number;
export const is_hot_reload_enabled: () => number;
export const collect_playhead_events: () => [number, number, number];
export const register_addon: (a: number, b: number) => [number, number, number];
export const register_sample: (a: number, b: number, c: any) => [number, number, number];
export const list_registered_banks: () => [number, number, number];
export const list_registered_samples: (a: number) => [number, number, number];
export const sample_load_events: (a: number) => [number, number, number];
export const collect_playback_debug: (a: number) => [number, number, number];
export const playback_debug_state: () => [number, number, number];
export const set_wasm_debug_errors: (a: number) => void;
export const collect_last_errors: (a: number) => [number, number, number];
export const collect_parse_errors: (a: number) => [number, number, number];
export const register_playhead_callback: (a: any) => any;
export const disable_hot_reload: () => void;
export const enable_hot_reload: (a: any) => void;
export const register_bank_json: (a: number, b: number) => [number, number];
export const register_bank_from_manifest: (a: number, b: number) => any;
export const load_bank_from_url: (a: number, b: number) => any;
export const get_render_metadata: (a: number, b: number, c: any) => [number, number, number];
export const export_audio: (a: number, b: number, c: any, d: number) => [number, number, number];
export const render_audio: (a: number, b: number, c: any) => [number, number, number];
export const debug_render: (a: number, b: number, c: any) => [number, number, number];
export const render_wav_preview: (a: number, b: number, c: any, d: number) => [number, number, number];
export const get_code_to_buffer_metadata: (a: number, b: number, c: any) => [number, number, number];
export const export_midi_file: (a: number, b: number, c: any, d: number) => [number, number, number];
export const render_midi_array: (a: number, b: number, c: any, d: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_export_5: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure1053_externref_shim: (a: number, b: number, c: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h6bc7bbf57d0f8b47: (a: number, b: number) => void;
export const closure1086_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
